spring:
  application:
    name: CATAMS

  mail:
    host: smtp.qq.com
    port: 465
    username: 1842640660@qq.com
    password: oohscbwwtcvobbda   # 这里填你在QQ邮箱生成的“授权码”
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

  datasource:
    url: jdbc:mysql://localhost:3308/catams?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8
    username: catams
    password: catams
    driver-class-name: com.mysql.cj.jdbc.Driver


  rabbitmq:
    host: localhost          # 本地开发用
#    host: catams-rabbitmq   # docker-compose 里定义的 service 名
    port: 5672
    username: admin
    password: admin

  data:
    redis:
      host: localhost
#      host: redis    # docker-compose 里定义的 service 名
      port: 6379
      database: 0

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  cache:
    type: redis

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    serialization:
      write-dates-as-timestamps: false

server:
  port: 9000

catams:
  auth:
    token:
      prefer: true          # true=优先 Redis, false=强制用内存
      startup-check: true   # true=启动时 ping Redis

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: info
    com.usyd.catams: debug
